name: vonette_web
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  fl_chart: ^0.55.2
  scaled_app: ^0.2.3
  flutter_switch: ^0.3.2
  shared_preferences: ^2.0.15

  #firebase
  firebase_auth: ^4.2.3
  google_sign_in: ^5.4.1
  cloud_firestore: ^4.3.0
  provider: ^6.0.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  bubble: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/fbla-logo.jpg
    - assets/images/profile_pic.png
    - assets/images/profile_pic1.png
    - assets/images/vonette_logo.png
    - assets/images/google_logo.png

