List tempUserVals = [
  [
    'Aadhithya Arun',
    '2011563@apps.nsd.org',
    9,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Danial Aghassi',
    '8479545@apps.nsd.org',
    12,
    [
      'Travis Scott',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Rushil Arumugam',
    '7894359@apps.nsd.org',
    10,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Yashwant Datti',
    '4358799@apps.nsd.org',
    11,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Sathvik Chilakala',
    '7894359@apps.nsd.org',
    9,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Kim Singh',
    '3457989@apps.nsd.org',
    11,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Sai Praneth',
    '5434889@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Chendur Jayavelu',
    '2011563@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Surya Selvakumar',
    '8479545@apps.nsd.org',
    9,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Tanush Ganji',
    '7894359@apps.nsd.org',
    10,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Jay Panuganti',
    '4358799@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Sasi Kotapati',
    '7894359@apps.nsd.org',
    10,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Nikhil Vaidyanath',
    '3457989@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Aayam Baidya',
    '5434889@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Aayush Talati',
    '2011563@apps.nsd.org',
    11,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Pranav Menon',
    '8479545@apps.nsd.org',
    9,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Akchara Arun',
    '7894359@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Arun Mani',
    '4358799@apps.nsd.org',
    10,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Akila Arun',
    '7894359@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Nivesri Parthiban',
    '3457989@apps.nsd.org',
    9,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Rishi Ponnaganti',
    '5434889@apps.nsd.org',
    11,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Pranay Nandkeolyar',
    '2011563@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Arav Popli',
    '8479545@apps.nsd.org',
    10,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Purannan Balakrishnan',
    '7894359@apps.nsd.org',
    12,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Kanye West',
    '4358799@apps.nsd.org',
    9,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Kid Cudi',
    '7894359@apps.nsd.org',
    11,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Polo G',
    '3457989@apps.nsd.org',
    10,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
  [
    'Travis Scott',
    '5434889@apps.nsd.org',
    9,
    [
      'Selena Gomez',
      'Kanye West',
      'Peter Pan',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun'
    ],
    [
      'HOSA',
      'CS Club',
      'FBLA',
      'TSA',
      'DECA',
      'Math Club',
      'BSU',
      'ISA',
      'PSU'
    ],
  ],
];
