List tempClubVals = [
  [
    'Kayla Francisco',
    'kfrancisco@nsd.org',
    'A-Che',
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
    [
      'High School and Beyond Plan',
      'UC College Rep Coming',
      'Naviance',
      'Meet with students',
    ],
  ],
  [
    'Tiffany Frane',
    'tfrane@nsd.org',
    'Chh-Gr',
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
    [
      'High School and Beyond Plan',
      'UC College Rep Coming',
      'Naviance',
      'Meet with students',
    ],
  ],
  [
    'Jeff Dennis',
    'jdennis@nsd.org ',
    'Gs-La',
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
    [
      'High School and Beyond Plan',
      'UC College Rep Coming',
      'Naviance',
      'Meet with students',
    ],
  ],
  [
    'Nancy Smith-Vela',
    'nvela@nsd.org',
    'Lb-O',
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
    [
      'High School and Beyond Plan',
      'UC College Rep Coming',
      'Naviance',
      'Meet with students',
    ],
  ],
  [
    'Heatherjoy Boi',
    'hboi@nsd.org',
    'P-SL',
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
    [
      'High School and Beyond Plan',
      'UC College Rep Coming',
      'Naviance',
      'Meet with students',
    ],
  ],
  [
    'Dawn LaMance',
    'dlamance@nsd.org',
    'Sm-Z',
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
    [
      'High School and Beyond Plan',
      'UC College Rep Coming',
      'Naviance',
      'Meet with students',
    ],
  ],
];
