List tempClubVals = [
  [
    'FBLA',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'TSA',
    'steachout@apps.nsd.org',
    '2011432@apps.nsd.org',
    [
      'Spencer Teachout',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'HOSA',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'PSA',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'ISA',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'CS Club',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'SSG',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'SSS',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'DECA',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'GSA',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
  [
    'BSU',
    'ibarnes@apps.nsd.org',
    '2011783@apps.nsd.org',
    [
      'Ian Barnes',
      'Rushil Arumugam',
      'Chendur Jayavelu',
      'Sathvik Chilakala',
      'Danial Aghassi',
      'Yashwant Datti',
    ],
    [
      'Kim Singh',
      'Nikhil Vaidayanath',
      'Arun Mani',
      'Akila Arun',
      'Akchara Arun',
      'Rajesh Arumugam',
      'Saravana Jayavelu',
      'Tanush Ganji',
      'Surya Selvakumar',
      'Shashank Kotapati',
      'Aayush Talati',
      'Jayaharsha Panuganti',
      'Kevin Chen',
      'Aarav Talati',
      'Aayush Talati',
    ],
  ],
];
